### ISSUE TITLE
Error: Error storing file to the images store: undefined

### ISSUE THREAD

**Issue by trinisofttechnologies** [CollectionFS/Meteor-CollectionFS#1002]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error storing file to the images store: undefined
    at [object Object].<anonymous> (packages/cfs_collection.js:121:19)
    at emitThree (events.js:97:13)
    at [object Object].emit (events.js:175:7)
    at Writable.<anonymous> (packages/cfs_storage-adapter.js:249:26)
    at emitOne (events.js:82:20)
    at Writable.emit (events.js:169:7)
    at packages/cfs_dropbox.js:337:19
    at /app/programs/server/npm/node_modules/meteor/cfs_dropbox/node_modules/dropbox/lib/dropbox.js:1458:18
    at Client.Dropbox.Client.Client._handleXhrError (/app/programs/server/npm/node_modules/meteor/cfs_dropbox/node_modules/dropbox/lib/dropbox.js:2161:7)
    at Xhr.onError (/app/programs/server/npm/node_modules/meteor/cfs_dropbox/node_modules/dropbox/lib/dropbox.js:1075:24)

==========================
What kind of error could this be?

This error doesn't show up on development env, but shows up on production env.

**Comment by nooitaf** [comment]
You could add `FS.debug=true` in global code to get more info.
You could try `meteor --production` locally and see if you get the same error.

**Comment by trinisofttechnologies** [comment]
Ok, will do so and put the log.

It doesn't happen if I do meteor --production

**Comment by Fotso** [comment]
I get the same error on my apps localy when I try to store image with dropbox... 
Did you finaly find where the problem come from?

**Comment by Kuperz** [comment]
I got the same problem; anybody?

**Comment by chandan1794** [comment]
I got the same error, too. Please help!

**Comment by nooitaf** [comment]
maybe related https://github.com/CollectionFS/Meteor-CollectionFS/issues/1015
