### ISSUE TITLE
Accessing url from serverside

### ISSUE THREAD

**Issue by Chaosbohne** [CollectionFS/Meteor-CollectionFS#283]
Is it possible to access the url attribute of an image on serverside?

I'd like to store the url in another collection to avoid doing some joins. 

Does the url change over time or is this property constant after the uploadprocess is completed?

Code:

```
 var image = Images.findOne({_id : imageId });
 Images.url({store : 'images'})
```

Error on serverside:

```
Exception while invoking method 'setImage' TypeError: Object #<Object> has no method '_storedLoginToken'                       
```

**Comment by EvilJohnny** [comment]
Hello, I think I am facing this problem also... It was fixed using ```auth: false```

This is my server code, I am using it to save the user Facebook image to my server (I am using S3):

```javascript
//Create new image FS File
fsFile = new FS.File(facebookImgURL);
fsFile.metadata = {
	ownerId: user._id
};
		
AccountImages.insert(fsFile, function (err, fileObj) {
	console.log('OK, file inserted');
			
	var onStored = Meteor.bindEnvironment(function() {
		console.log('file uploaded');
		console.log(fileObj.url({store:'accountImage', auth:false}));
		console.log(fileObj.isUploaded());
	}, function(error) {
		throw error;
	});
			
	fileObj.once('stored', onStored);
});
```
Without  ```auth: false``` I just get "null" in the console log.

BTW @aldeed , another related doubt is if I am doing the correct process to get the file after being uploaded. That is, using ```Meteor.bindEnvironment```. I am doing it that way because calling ```fileObj.url()``` was causing the following error:

```
W20150818-11:47:44.400(2)? (STDERR)
W20150818-11:47:44.400(2)? (STDERR) C:\Users\juanb\AppData\Local\.meteor\packages\cfs_s3\0.1.3\npm\node_modules\aws-sdk\lib\request.js:32
W20150818-11:47:44.400(2)? (STDERR)           throw err;
W20150818-11:47:44.400(2)? (STDERR)                 ^
W20150818-11:47:44.400(2)? (STDERR) Error: Can't wait without a fiber
W20150818-11:47:44.400(2)? (STDERR)     at Function.wait (C:\Users\juanb\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:155:9)
W20150818-11:47:44.400(2)? (STDERR)     at Object.Future.wait (C:\Users\juanb\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:397:10)
W20150818-11:47:44.400(2)? (STDERR)     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
W20150818-11:47:44.401(2)? (STDERR)     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:973:1)
W20150818-11:47:44.401(2)? (STDERR)     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
W20150818-11:47:44.401(2)? (STDERR)     at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:997:1) W20150818-11:47:44.401(2)? (STDERR)     at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:812:1)
W20150818-11:47:44.401(2)? (STDERR)     at [object Object].MongoConnection.findOne (packages/mongo/mongo_driver.js:718:1)
W20150818-11:47:44.401(2)? (STDERR)     at [object Object]._.extend.findOne (packages/mongo/collection.js:296:1) W20150818-11:47:44.401(2)? (STDERR)     at EventEmitter.FS.File.getFileRecord (packages/cfs:file/fsFile-common.js:236:1)
=> Exited with code: 8
```

So after reading a little (I am still a newbie with Meteor...) I used ```Meteor.bindEnvironment```, and seems to work perfect. But I am just doubting if I am taking a wrong path to do this.

Thanks!!

**Comment by EvilJohnny** [comment]
Hhhmm... ok, you can partially forget my previous comment... I think yesterday was just a matter of luck or something. Today is giving me "null" despite using ```auth: false```.

The thing is that the line ```console.log(fileObj.isUploaded());``` is returning ```true```, so I don't know why the url call is giving me null :disappointed:

**Comment by EvilJohnny** [comment]
Finally I make it work with:

```javascript

//Create new image FS File
fsFile = new FS.File(facebookImgURL);
fsFile.metadata = {
	ownerId: user._id
};
		
AccountImages.insert(fsFile, function (err, fileObj) {
	var urlRetrieveCount = 0;
			
	var onStored = Meteor.bindEnvironment(function() {
		if (urlRetrieveCount > 2) {
			console.log('Too much url retrieval attempts for the image. Aborting');
		} else {
			var accountImageURL = fileObj.url({store:'accountImage'}),
				accountThumbnailURL = fileObj.url({store:'accountThumbnail', auth:false});

			if (!accountImageURL || !accountThumbnailURL) {
				urlRetrieveCount++;
				setTimeout(onStored, 2000);
			} else {
				Meteor.call('saveAccountImageData', {
					accountImage: accountImageURL,
					accountThumbnail: accountThumbnailURL
				});
			}
		}
	}, function(error) {
		throw error;
	});
			
	fileObj.once('stored', onStored);
});
```

But I don't feel is the best approach... :confused: 

Maybe there is a different event that fires when the urls are already "computed" or something?
