### ISSUE TITLE
Object #<Object> has no method 'allowsFile' when inserting file server-side

### ISSUE THREAD

**Issue by willemx** [CollectionFS/Meteor-CollectionFS#517]
I get this error when inserting a file server-side. When inserting client-side, everything works ok. 

    Exception while invoking method 'importZip' TypeError: Object #<Object> has no method 'allowsFile'
    I20150124-19:30:20.830(1)?     at checkAndInsert (packages/cfs:collection/api.common.js:41:1)
    I20150124-19:30:20.830(1)?     at attachDataCallback (packages/cfs:collection/api.common.js:85:1)
    I20150124-19:30:20.830(1)?     at setName (packages/cfs:file/fsFile-common.js:143:1)
    I20150124-19:30:20.830(1)?     at setData (packages/cfs:file/fsFile-common.js:123:1)
    I20150124-19:30:20.830(1)?     at EventEmitter.fsFileAttachData [as attachData] (packages/cfs:file/fsFile-common.js:94:1)
    I20150124-19:30:20.831(1)?     at FS.Collection.insert (packages/cfs:collection/api.common.js:81:1)
    I20150124-19:30:20.831(1)?     at packages/meteor/helpers.js:118:1
    I20150124-19:30:20.831(1)?     at readMediaFromFile (app/server/export-import.js:56:21)
    I20150124-19:30:20.831(1)?     at app/server/export-import.js:168:29
    I20150124-19:30:20.831(1)?     at readFileLines (app/server/file-io.js:94:13)

I do have allow rules set up:

    Mediafiles = new FS.Collection('mediafiles', {
            stores: [new FS.Store.GridFS('mediafiles', {})]
        });
    
    Mediafiles.allow({
        insert: function(userId, doc) {
            return true;
        },
    
        download: function(userId, fsFile) {
            return true;
        },
    
        update: function(userId, doc, fields, modifier) {
            return true;
        }
    });

**Comment by willemx** [comment]
never mind, it was my own fault (did something stupid with Meteor.wrapAsync)...
