### ISSUE TITLE
Unspecified error on production crashed server

### ISSUE THREAD

**Issue by bitomule** [CollectionFS/Meteor-CollectionFS#532]
We've a running app today it crashed while uploading a file.

on('error')

event was called but it doesn't give any info, just file and store info.

Log shows this:

    TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at [object Object].<anonymous> (packages/cfs:collection/common.js:94:1)
    at [object Object].emit (events.js:106:17)
    at Writable.<anonymous> (packages/cfs:storage-adapter/storageAdapter.server.js:203:1)
    at Writable.emit (events.js:117:20)
    at Response.<anonymous> (packages/cfs:s3/s3.upload.stream2.js:152:1)
    at Request.<anonymous> (/opt/myapp/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/opt/myapp/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/opt/myapp/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

Any idea on what could be the problem?

Any way to avoid this?

I've tried but can't find a way to reproduce it.

Thanks!

**Comment by raix** [comment]
Its on the trello as a high priority - we need better error handling / in order to debug
