### ISSUE TITLE
While checking for cfs:gridfs@0.0.30: error: No compatible build found

### ISSUE THREAD

**Issue by jasonxeno** [CollectionFS/Meteor-CollectionFS#581]
Getting this error when trying to update:
```
While checking for cfs:gridfs@0.0.30:
error: No compatible build found
```
OS is: Linux Ubuntu 14.04

Package list and update attempt:
```
$ meteor list
accounts-password                   1.0.6  Password support for accounts
alanning:roles                      1.2.13  Role-based authorization
aldeed:autoform                     4.2.2  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2                  2.3.2  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema                1.3.0  A simple schema validation object with reactivity. Used by collection2 and autoform.
aldeed:tabular                      1.1.0  Datatables for large or small datasets in Meteor
aldeed:template-extension           3.4.1  Adds template features currently missing from the templating package
aslagle:reactive-table              0.6.14  A reactive table designed for Meteor
base64                              1.0.2  Base64 encoding and decoding
cfs:graphicsmagick                  0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                          0.0.29* GridFS storage adapter for CollectionFS
cfs:s3                              0.1.2* Amazon Web Services S3 storage adapter for CollectionFS
cfs:standard-packages               0.5.3* Filesystem for Meteor, collectionFS
clinical:session-extended-api       1.0.0  Extends the Session API
ctjp:meteor-bootstrap-switch        3.3.1_3  Meteor package for https://github.com/nostalgiaz/bootstrap-switch
dandv:http-more                     1.0.7_1  Make HTTP calls to remote servers, passing any extra options to the underlying backend
dburles:collection-helpers          1.0.2  Transform your collections with helpers that you define
dburles:google-maps                 1.0.8  Google Maps Javascript API v3
dburles:spacebars-tohtml            1.0.0  Easily compile spacebars templates to html
email                               1.0.5  Send email messages
erasaur:meteor-lodash               3.3.0  Wrapper for Lo-Dash v3.3.0
flowkey:bowser                      1.0.0  Browser Detection for Meteor - powered by bowser js
fortawesome:fontawesome             4.2.0_2  Font Awesome (official): 470+ scalable vector icons, customizable via CSS, Retina friendly
francocatena:status                 1.1.2  Display the connection status with the server
hellogerard:reststop2               0.7.1  Add the ability to do RESTful APIs with Meteor 0.6.5.
iron:router                         1.0.7  Routing specifically designed for Meteor
kevohagan:sweetalert                0.4.2  a beautiful replacement for javascript's alert() 
matb33:collection-hooks             0.7.11  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
matdutour:outdated-browser          0.1.1  Detects outdated browsers and advises users to upgrade to a new version.
meteor-platform                     1.2.1  Include a standard set of Meteor packages in your app
meteorhacks:kadira                  2.19.6  Performance Monitoring for Meteor
meteorhacks:npm                     1.2.2  Use npm modules with your Meteor App
miguelalarcos:afwrap-xautocomplete  0.3.0  wrap over xautocomplete so it works ok with autoform
miguelalarcos:xautocomplete         0.3.0  An autocomplete widget. Values can be strings, array of strings or reference _ids.
mizzao:bootboxjs                    4.3.0  Programmatic dialog boxes using Twitter's bootstrap modals
mizzao:user-status                  0.6.4  User connection and idle state tracking for Meteor
momentjs:moment                     2.9.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
msavin:mongol                       0.5.4  The insanely handy development package for Meteor.
nahue:simple-line-icons             1.0.0  Simple Line Icons packaged for meteor
npm-container                       1.0.0+ Contains all your npm dependencies
pcel:serialize                      1.0.0  Serialize an HTML Form to a JavaScript Object
percolate:synced-cron               1.1.1  Allows you to define and run scheduled jobs across multiple servers.
raix:handlebar-helpers              0.2.4  Handlebar helpers
rclai89:cheerio                     1.0.0  Cheerio for Meteor
reactive-dict                       1.0.5  Reactive dictionary
reywood:publish-composite           1.3.5  Publish a set of related documents from multiple collections with a reactive join
risul:accounting                    1.0.0  Meteor package for Accounting.js - http://openexchangerates.github.io/accounting.js/
risul:chance                        1.0.1  Meteor package for Chance - Random generator helper for JavaScript: http://chancejs.com
sacha:spin                          2.0.4  Simple spinner package for Meteor
smeevil:syntax-error-notifier       1.0.6  Display a warning modal if your app crashes due to a syntax error, auto reloads on fix
starxeno:toolswrap                  0.0.1  Toolswrap
tmeasday:publish-counts             0.3.4  Publish the count of a cursor, in real time
twbs:bootstrap                      3.3.2  Bootstrap (official): the most popular HTML/CSS/JS framework for responsive, mobile first projects
useraccounts:bootstrap              1.8.1  Accounts Templates styled for Twitter Bootstrap.
yasinuslu:oneplace                  0.0.4  Keep everything in one place
zimme:bootstrap-hover-dropdown      2.0.11  Enable Bootstrap dropdowns to activate on hover

                                              
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated further, try typing `meteor add <package>@<newVersion>` to see more
  information.
                                              
+ These packages are built locally from source.
$ meteor update
This project is already at Meteor 1.0.3.2, the latest release.
=> Errors while upgrading packages:           
                                              
While checking for cfs:gridfs@0.0.30:
error: No compatible build found


```

**Comment by raix** [comment]
sorry about that, just bumped versions - publishing for arch... (we are building auto publish scripts atm. so this can be avoided)

(its trying to publish for arch atm - give it 5 min)

**Comment by robwatkin** [comment]
Just in case anyone else can't build, I just hit the same problem (20 hours later) on OSX. I tried 
$ meteor remove cfs:gridfs

then
$ meteor add cfs:gridfs
 => Errors while adding packages:
 While checking for cfs:gridfs@0.0.30:
error: No compatible build found

I was able to build with 
$ meteor add cfs:gridfs@=0.0.27

**Comment by yogiben** [comment]
Still not working.

Can confirm that `$ meteor add cfs:gridfs@=0.0.27` works.

**Comment by aldeed** [comment]
@raix, I'm starting to think this package ended up in some broken state that can't be fixed by bumping and republishing. It started with my attempt to publish it for the Windows preview, but since then I think we've both tried bumping the version and publishing from OSX, which seems to work but then somehow does not end up with an OSX-compatible build, even though that's the OS we used to publish?

Or is it also related to moving all our packages into a single repo? Have you tried copying the files for this package elsewhere and then publishing?

@stubailo?

**Comment by jasonxeno** [comment]
Tried doing meteor update today again.

```
$ meteor update
This project is already at Meteor 1.0.3.2, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
aslagle:reactive-table  upgraded from 0.6.14 to 0.6.15
cfs:access-point        upgraded from 0.1.43 to 0.1.44
cfs:base-package        upgraded from 0.0.27 to 0.0.28
cfs:collection          upgraded from 0.5.3 to 0.5.4
cfs:collection-filters  upgraded from 0.2.3 to 0.2.4
cfs:data-man            upgraded from 0.0.4 to 0.0.6
cfs:file                upgraded from 0.1.15 to 0.1.16
cfs:gridfs              upgraded from 0.0.29 to 0.0.30
cfs:s3                  upgraded from 0.1.2 to 0.1.3
cfs:standard-packages   upgraded from 0.5.3 to 0.5.4
cfs:storage-adapter     upgraded from 0.1.1 to 0.2.1
cfs:tempstore           upgraded from 0.1.3 to 0.1.4
cfs:upload-http         upgraded from 0.0.19 to 0.0.20
cfs:worker              upgraded from 0.1.3 to 0.1.4
msavin:mongol           upgraded from 0.5.4 to 0.5.5
```
It did not complain about incompatible build this time.

But now I am getting the same error as issue #588 on startup.

```
I20150305-11:25:25.244(-6)? Exception in queued task: TypeError: Cannot read property 'start' of undefined
I20150305-11:25:25.245(-6)?     at Object.FS.StorageAdapter.createReadStream (packages/cfs:gridfs/gridfs.server.js:78:1)
I20150305-11:25:25.245(-6)?     at Object.self.adapter.createReadStreamForFileKey (packages/cfs:storage-adapter/storageAdapter.server.js:71:1)
I20150305-11:25:25.245(-6)?     at Object.self.adapter.createReadStream (packages/cfs:storage-adapter/storageAdapter.server.js:79:1)
I20150305-11:25:25.245(-6)?     at packages/cfs:tempstore/tempStore.js:364:1
I20150305-11:25:25.245(-6)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150305-11:25:25.245(-6)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150305-11:25:25.245(-6)?     at CombinedStream._getNext (/home/jason/.meteor/packages/cfs_tempstore/.0.1.4.1kimx01++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:83:3)
I20150305-11:25:25.245(-6)?     at CombinedStream.resume (/home/jason/.meteor/packages/cfs_tempstore/.0.1.4.1kimx01++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:132:10)
I20150305-11:25:25.245(-6)?     at CombinedStream.pipe (/home/jason/.meteor/packages/cfs_tempstore/.0.1.4.1kimx01++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:64:8)
```

**Comment by stubailo** [comment]
@raix @aldeed I don't really want to wade through a bunch of stack traces and try to solve this issue over GitHub comments - do you guys have an opportunity to get on a Google hangout sometime soon to take a look?

**Comment by aldeed** [comment]
@stubailo I don't think there is a need. I seem to have 0.0.30 published correctly for all archs now, I think we were running into a combination of the window-preview issue and https://github.com/meteor/meteor/issues/3676 at the same time, which made it difficult to understand what was going on. Hopefully we can do a windows preview build at some point, but I'm not anxious to go through that confusion of errors again.

**Comment by stubailo** [comment]
I fixed some of the errors we had with incorrect version numbers, so in theory it should just work on Windows now. It would actually be really helpful for us to test whether it works, but I guess I can just do that by cloning your package and publishing under my name.

**Comment by aldeed** [comment]
If you think it will work, I can try again. In theory I know how to get out of the potential mess now.

**Comment by stubailo** [comment]
Nah, I'll try it first and let you know.

**Comment by obiwarn** [comment]
I get the same error as jasonxeno.

downgrading to 
`meteor add cfs:gridfs@=0.0.27`
works

**Comment by aaronjudd** [comment]
@aldeed now I get this with 0.0.31 

```
   While checking for cfs:gridfs@0.0.31:
   error: No compatible build found
```

**Comment by jasonxeno** [comment]
With the release of cfs:gridfs@0.0.31, I can successfully update everything without the previous errors and it works now.

**Comment by mesosteros** [comment]
I'm actually still getting this error. And it also happens for 0.0.27

**Comment by antoinesab** [comment]
Hi there!
I tried with 0.0.32 and it didn't work but
meteor add cfs:gridfs@=0.0.33 works for me.
Meteor version Meteor 1.1-rc.0 (Windows preview https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows)
I hope this will help you.

**Comment by aldeed** [comment]
`0.0.33` is the first release with support for Windows.
