### ISSUE TITLE
No valid replicaset instance servers found

### ISSUE THREAD

**Issue by Ethaan** [CollectionFS/Meteor-CollectionFS#586]
Today while i made a deploy into my production server (hosted on modulus.io), i start get this message.

```javascript
Error: No valid replicaset instance servers found
    at Object.Future.wait (/mnt/data/1/node_modules/fibers/future.js:326:15)
    at packages/meteor/helpers.js:119:1
    at new FS.StorageAdapter (packages/cfs:storage-adapter/storageAdapter.server.js:252:1)
    at new FS.Store.GridFS (packages/cfs:gridfs/gridfs.server.js:46:1)
    at app/lib/collection.js:61:12
    at app/lib/collection.js:185:3
    at /mnt/data/1/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/data/1/node_modules/underscore/underscore.js:79:11)
    at /mnt/data/1/programs/server/boot.js:116:5
    - - - - -
    at /mnt/data/1/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:464:45
    at [object Object].<anonymous> (/mnt/data/1/node_modules/mongodb/lib/mongodb/connection/server.js:559:7)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/mnt/data/1/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/mnt/data/1/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:833:16
    at process._tickDomainCallback (node.js:463:13)
```

This ```no valid replicaset``` its associated with the FSCollection Package?

Thanks for the help

**Comment by raix** [comment]
remove the instances and try again - this is not a FS specific issue.

**Comment by Ethaan** [comment]
@raix yep you are right it was a hosting error with the db
