### ISSUE TITLE
Request for non existing file crashing meteor app 

### ISSUE THREAD

**Issue by emmanuelbuah** [CollectionFS/Meteor-CollectionFS#590]
Below is an crash error when request a file that doesn't exist. Crashing meteor should be avoided if possible. Will it be possible to wrap file retrieval with a try and catch + log so the app doesn't crash.
![screen shot 2015-03-05 at 1 02 33 pm](https://cloud.githubusercontent.com/assets/432664/6514604/90c363ca-c338-11e4-944d-c872205f2cb8.png)

```
I20150305-12:56:25.506(-8)? GET FILERECORD: Ax6Ffy8Lx2sKktPww
I20150305-12:56:25.507(-8)? Read file "IMG_20150228_120945296.jpg" bytes 0--1/0
I20150305-12:56:25.507(-8)? createReadStream ImagesLarge
I20150305-12:56:25.507(-8)? createReadStreamForFileKey ImagesLarge

http.js:731
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:731:11)
    at ServerResponse.writeHead (http.js:1152:20)
    at ProxyServer.<anonymous> (/Users/emmanuelbuah/.meteor/packages/meteor-tool/.1.0.41.1atjma7++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-proxy.js:96:21)
    at ProxyServer.emit (/Users/emmanuelbuah/.meteor/packages/meteor-tool/.1.0.41.1atjma7++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/Users/emmanuelbuah/.meteor/packages/meteor-tool/.1.0.41.1atjma7++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
    at ClientRequest.emit (events.js:117:20)
    at Socket.socketOnData (http.js:1592:9)
    at TCP.onread (net.js:527:27)
``

**Comment by emmanuelbuah** [comment]
I'm also wonder if it has something to do the http lib trying to send a file with 0 bytes. I had a few 0 byte files due to an issue with imagemagick.

**Comment by rhyslbw** [comment]
Better managing the errors is being tracker in https://github.com/CollectionFS/Meteor-CollectionFS/issues/562
