### ISSUE TITLE
Exception in queued task: Error: Storage name already exists: "_tempstore"

### ISSUE THREAD

**Issue by subhog** [CollectionFS/Meteor-CollectionFS#591]
I started to get the following error today in a production application:

```
Exception in queued task: Error: Storage name already exists: "_tempstore"
    at new FS.StorageAdapter (packages/cfs:storage-adapter/storageAdapter.server.js:37:1)
    at new FS.Store.GridFS (packages/cfs:gridfs/gridfs.server.js:46:1)
    at mountStorage (packages/cfs:tempstore/tempStore.js:70:1)
    at EventEmitter.fsTempStoreRemoveFile [as removeFile] (packages/cfs:tempstore/tempStore.js:176:1)
    at Object.fsCollection.files.find.observe.removed (packages/cfs:worker/fileWorker.js:59:1)
    at [object Object].observeChangesCallbacks.removed (packages/minimongo/observe.js:169:1)
    at self.applyChange.removed (packages/minimongo/observe.js:71:1)
    at packages/mongo/observe_multiplex.js:163:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
```

Before today everything worked without problems. I did remove a few files in the meantime and that was the only change related to CollectionFS. What can be the possible cause? There's no hint in the error description and it appears pretty random.

**Comment by subhog** [comment]
Restarting the app solve the problem. However, this interrupted work for our users and I'd like to know what caused this bug so that we can avoid it in the future.

**Comment by aldeed** [comment]
I think it's a timing issue that is a known issue.

**Comment by rhyslbw** [comment]
Similar error here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/267

@aldeed Is this known error tracking in an existing issue?

**Comment by aldeed** [comment]
As I recall, it's related to this [bit of code](https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/tempstore/tempStore.js#L56-L80) where we define the temp store only when it's needed, but somehow it's getting called twice, some kind of timing issue. I don't think we were ever able to isolate the cause. Defining it later is essentially a workaround for a circular dependency we have, as explained in the code comments. There may be other ways we can work around that.

**Comment by aldeed** [comment]
To keep it really simple, we could just use GridFS always and ditch the fancy logic, which would not require waiting for the worker pkg to load. Or we could require that the app call a `config` function in startup code. Any ideas @raix?

**Comment by raix** [comment]
Maybe we should move the tempstore selection to Meteor.settings - would prevent load order?

**Comment by aldeed** [comment]
Sounds good to me

**Comment by raix** [comment]
another idea - is to use the EventState package instead of EventEmitter - we could event states / levels for the system to start up.
eg.:
* initialize / startup
* test system
* migrate data
* test data
* ready

Just a general idea

**Comment by rhyslbw** [comment]
Is there a reason why a tempstore can't be defined per FS.Collection, passed in as an option to the constructor if you want to override the default?

**Comment by aldeed** [comment]
@rhyslbw That might work but I doubt there would ever be a good reason to use different temp store SAs for different collections.

**Comment by rhyslbw** [comment]
@aldeed how's this scenario:
Collection A has only Filesystem managing images being imported from a path on the server. The database is hosted externally, so it makes sense for the temp files to be a filesystem SA for performance IO. In the same app Collection B, C, D have just GridFS stores managing lower volume assets.  These collections are now dependant on a single server, whereas ideally the temp data would just be available from the db for redundancy in the case of server failure, or the potential for a remote worker to have access to the file data if observing changes on a cfs._tempstore.chunks collection. 

Maybe making GridFS the default temp store with a custom temp store FS.Collection constructor option would be a good balance?

**Comment by raix** [comment]
We should perhaps have the main collectionFS imply package include some minor code for wiring up the packages - this would also help us limit the inter package dependencies (makes bumping versions a pain at the moment)

So the main imply package could create an instance of tempstore setting the appropriate SA - then pass that on to the accesspoint etc. for them to reference?

(let me know if it doesnt make sense)

**Comment by aldeed** [comment]
@raix having the imply package set it up makes sense to me. Seems like an easy change we could make that would fix the random errors.

@rhyslbw collection overrides might make some sense, but it would be a larger project to update various pkg code to check for specific temp stores. Maybe we should do @raix idea of configuring in the imply pkg as the quick fix and then create a separate issue for the idea of collection-specific temp stores.

**Comment by rhyslbw** [comment]
Agreed. Just wanted the float the case now while it's hot

**Comment by derwaldgeist** [comment]
Bump. Just ran into the same problem. Tried to insert 3 files with Base64 content, but only 1 file was added. For the other two, the exception was thrown.

**Comment by Ragsboss** [comment]
+1 we are also hitting this issue randomly on different servers. Even our daily Jenkins builds started to fail randomly with this error.
