### ISSUE TITLE
Exception thrown creating read stream

### ISSUE THREAD

**Issue by AndyWilkinUK** [CollectionFS/Meteor-CollectionFS#597]
So the first thing I will say is that my code was working a couple of months back (sure you hear this a lot). I'm using GridFS and Aldeed's cfs:autoform package to upload a small image.

The upload appears to work fine, but when trying to retrieve the file I get:
```
I20150307-23:08:23.412(0)? Exception in queued task: TypeError: Cannot read property 'start' of undefined
I20150307-23:08:23.413(0)?     at Object.FS.StorageAdapter.createReadStream (packages/cfs:gridfs/gridfs.server.js:78:1)
I20150307-23:08:23.413(0)?     at Object.self.adapter.createReadStreamForFileKey (packages/cfs:storage-adapter/storageAdapter.server.js:71:1)
I20150307-23:08:23.413(0)?     at Object.self.adapter.createReadStream (packages/cfs:storage-adapter/storageAdapter.server.js:79:1)
I20150307-23:08:23.414(0)?     at packages/cfs:tempstore/tempStore.js:364:1
I20150307-23:08:23.414(0)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150307-23:08:23.414(0)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150307-23:08:23.414(0)?     at CombinedStream._getNext (/Users/awilkin/.meteor/packages/cfs_tempstore/.0.1.4.8n7vsc++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:83:3)
I20150307-23:08:23.414(0)?     at CombinedStream.resume (/Users/awilkin/.meteor/packages/cfs_tempstore/.0.1.4.8n7vsc++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:132:10)
I20150307-23:08:23.414(0)?     at CombinedStream.pipe (/Users/awilkin/.meteor/packages/cfs_tempstore/.0.1.4.8n7vsc++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:64:8)
I20150307-23:08:23.414(0)?     at saveCopy (packages/cfs:worker/fileWorker.js:176:1)
```

It does not even appear to generate the URL to download and am using a simple template. Rather than upload a load of extracts would you be able to please point me in the right direction or what other information you need.

On another note I still get this warning at startup:
```
I20150307-23:07:26.963(0)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
```

Thanks in advance.

**Comment by darkship** [comment]
I have this error too after updating to <code>cfs:standard-packages@0.5.4</code>. And unfortunately  I'm not able to go back to <code>cfs:standard-packages@0.5.3</code>, it is stuck.

**Comment by KristerV** [comment]
yep, this has got me too. My app worked yesterday :) Exactly the same error.

**Comment by darkship** [comment]
@KristerV I didn't know that you could lock it. This helped, thanks.

**Comment by rhyslbw** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/issues/588
