### ISSUE TITLE
Server crashes on image upload 

### ISSUE THREAD

**Issue by sacdallago** [CollectionFS/Meteor-CollectionFS#619]
Dear community,

my server crashes when uploading images. It seems the problem occurs with large files only. I have browsed previous issues and could not find a solution to solve my problem.

About my project: I removed insecure and I reduce the file size when uploading images using graphicsmagick/imagemagick. When uploading images I always get a "Access denyed" error, which depends on the allow conditions on the server. BUT, I tried to add the insecure package again, though the following error, the one I'm actually reporting, still occurs.

The error I get on the server is the following:

```
W20150322-15:20:19.904(1)? (STDERR) 
W20150322-15:20:19.905(1)? (STDERR) /home/chdallago/.meteor/packages/meteor-tool/.1.0.43.982l4p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150322-15:20:19.905(1)? (STDERR) 						throw(ex);
W20150322-15:20:19.905(1)? (STDERR) 						      ^
W20150322-15:20:19.958(1)? (STDERR) TypeError: Cannot read property 'keys' of undefined
W20150322-15:20:19.958(1)? (STDERR)     at packages/cfs:tempstore/tempStore.js:297:1
W20150322-15:20:19.959(1)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
=> Exited with code: 8
```

After the server crashes and before it restarts (thus clearing out the console) I get this on chrome:
```
Error: "Queue" failed [503] Unexpected error. [undefined], Error: failed [503] Unexpected error. [undefined]
 at upload-http-client.js:33
 at http-call-client.js:69
 at _.once (underscore.js:750)
 at XMLHttpRequest.xhr.onreadystatechange (http-call-client.js:192)power-queue.js:486 PowerQueue.runTaskDonepower-queue.js:568 taskCallbackDoneupload-http-client.js:33 (anonymous function)http-call-client.js:69 (anonymous function)underscore.js:750 _.oncehttp-call-client.js:192 xhr.onreadystatechange
```

The code related to the collection I'm using is:
server/storage.js
```
FS.HTTP.setBaseUrl('/images');
Images = new FS.Collection("images", {
    stores: [new FS.Store.GridFS("images", {
        transformWrite: function(fileObj, readStream, writeStream) {
            try{
                gm(readStream, fileObj.name()).resize('500').stream().pipe(writeStream);
            } catch (error){
                throw new Meteor.Error(error);
            }
        }
    })],
    filter: {
        allow: {
            contentTypes: ['image/*'] //allow only images in this FS.Collection
        }
    }
});
Images.allow({
    insert: function(userId, doc) {
        return (userId && Meteor.users.findOne(userId).username);
    },
    update: function(userId, doc, fields, modifier) {
        // No updates can be made!
        return false;
    },
    remove: function(userId, doc) {
        // can only remove your own documents
        return userId && Offers.findOne({
            file: doc._id
        }).reseller === userId;
    },
    download: function() {
        return true;
    },
    fetch: ['_id']
});
Meteor.publish('images', function(criteria, projection) {
    criteria = criteria || {};
    projection = projection || {};
    if (criteria.$or && criteria.$or.length < 0) {
        delete criteria.$or;
    }
    return Images.find(criteria, projection);
});
```

client/storage.js
```
FS.HTTP.setBaseUrl('/images');

Images = new FS.Collection("images", {
	stores : [new FS.Store.GridFS("images")],
	filter : {
		allow : {
			contentTypes : ['image/*'] //allow only images in this FS.Collection
		}
	}
});

imagesHandle = null;

Tracker.autorun(function() {
	var active = {
		$or : []
	};
	Offers.find({}, {
		fields : {
			file : 1
		}
	}).forEach(function(obj) {
		if (obj.file) {
			active.$or.push({
				_id : obj.file
			});
		}
	});

	if (active.$or.length > 0) {
		imagesHandle = Meteor.subscribe('images', active);
	}
});
```

be glad for any advise you can give me! Cheers

**Comment by nooitaf** [comment]
Large image files get even larger in memory because of decompression and that might be just too much for your servers memory.  

I'm not sure about the `allow update`. As far as i know, if you upload chunks of data, the first will be an insert and the rest will be updates, so you might have to allow the update.

**Comment by sacdallago** [comment]
Hi Nooitaf,

thanks for your reply! I will have a look at the system stats when uploading images to see if the process runs out of memory. For now I noticed the problem happens on production and also on all development machines, which in some cases are 16GB RAM/xeon machines that just run that one meteor instance, that's why at first sight I though it was weird. I'll post results here!

I will allow updates and see if that helps, will post results for that here too!

Thanks again,
Cheers

**Comment by nooitaf** [comment]
16GB should not be a problem. I had problems with 512MB and 1GB machines.

**Comment by rhyslbw** [comment]
How did you go with this @sacdallago ?

**Comment by sacdallago** [comment]
Hey! Sorry for not coming back.

I tried a mixture of everything, but it crashes anyway, even with small images, even with update method allowed (return true). It seems to depend on the upload stream breaking, that's why it is more likely to happen when uploading big images. So one scenario I noticed immediately triggers the error is: I upload an image and do not wait until it is uploaded to the server and start uploading another images AND try to delete the one that is being uploaded. I explain this a little bit better: I have a profile picture "drop zone", and when I drop an image there it triggers an insert on the images collection and in the callback function for the insert I have a delete on the same collection for the previous profile picture.

I tried to limit the mechanism, which means, you cannot update your profile picture until the image is not fully uploaded to the server, but still it crashes, also randomly. Like, uploading an image, 1mb, bam: crash. I just accepted it for now, but I hope it will be fixed :P

**Comment by sacdallago** [comment]
This might help understand:

```
'change #image' : function(event) {
        var target = $(event.target);
        var profile = this;
        var previous = profile.file;

        if(target[0].files[0].size > 3000000){
            renderMessage("Attenzione","Il file caricato è troppo grande! Caricare un file più piccolo, massimo 3 mb",4000);
            return;
        }

        FS.Utility.eachFile(event, function(file) {
            Images.insert(file, function(error, fileObj) {
                //Inserted new doc with ID fileObj._id, and kicked off the data upload using HTTP
                if (!error) {
                    Profile.update({
                        _id : profile._id
                    }, {
                        $set : {
                            file : fileObj._id
                        }
                    }, function(err){
                        if(!err){
                            Images.remove(previous);
                        }
                    });
                } else {
                    console.log(error);    
                }
            });
        });

        return;
    }
```

**Comment by nooitaf** [comment]
One problem i see is that if the insert doesn't throw an error it will update the profile and if that doesn't throw an error it removes the image. Also you might want to use the `fileObj._id` instead of `previous.file`

`````javascript
'change #image' : function(event) {
        var target = $(event.target);
        var profile = this;
        // var previous = profile.file;      <-------

        FS.Utility.eachFile(event, function(file) {
            Images.insert(file, function(error, fileObj) {
                if (!error && fileObj) {               // <---------
                    Profile.update({
                        _id : profile._id
                    }, {
                        $set : {
                            file : fileObj._id
                        }
                    }, function(err){
                        if(err){                        // <---------
                            Images.remove(fileObj._id); // <---------
                        }
                    });
                } else {
                    console.log(error);    
                }
            });
        });

        return;
    }
`````

Dunno if this is the solution to your problem though, a minimal repo might be better...

**Comment by mkim-hj** [comment]
was this ever addressed?

**Comment by mngkvn** [comment]
Sometimes it also triggers on my machine with even just a single upload and results to a broken image upload.

**Comment by sacdallago** [comment]
For a not-related project I noticed this happening at the nginx level (there was a nginx rule bloacking requests with payload bigger than X).
I cannot verify if that was the case with the initial problem though, cause I quit that job.

If someone has the possibility to reproduce, I think it would help out the community
