### ISSUE TITLE
Server crash on retrieval of SVG data

### ISSUE THREAD

**Issue by friendtogeoff** [CollectionFS/Meteor-CollectionFS#648]
Hello,

I'm fighting an issue with my Meteor app. I think that I'm following the documentation pretty much to the letter but I cannot seem to get past this one.

The application uses several FS.Collection instances, all using FS.Store.GridFS. Some store image data, but one in particular is used for .SVG file data. Only this one suffers from a server crash when .SVG files are requested by the client.

I can cause the crash by manually requesting the URL (as returned by FS.file.url()) for the file from the browser, without any client code interaction. The file is correctly delivered but then the server crashes. If I store PNG data in the same collection and retrieve it by requesting the URL then everything completes smoothly without error.

The problem occurs with the simplest of SVG files (see attached .png copy of an example), and I've reproduced it with an FS.Collection with only one file in it.

Any ideas or suggestions most welcome

console output with FS.debug = true :

I20150410-13:22:23.755(1)? GRIDFS { _id: 5527c82760aa8f3f0b737f94,
I20150410-13:22:23.755(1)?   root: 'cfs_gridfs.placeThumbs',
I20150410-13:22:23.755(1)?   range: { startPos: 0, endPos: 115675 } }
I20150410-13:22:23.755(1)? Read file "test3.svg" bytes 0-1198/1199
I20150410-13:22:23.755(1)? createReadStream placePlans
I20150410-13:22:23.756(1)? createReadStreamForFileKey placePlans
I20150410-13:22:23.756(1)? GRIDFS { _id: 5527cd21dc2a66120c1f40d3,
I20150410-13:22:23.756(1)?   root: 'cfs_gridfs.placePlans',
I20150410-13:22:23.756(1)?   range: { startPos: 0, endPos: 1198 } }
W20150410-13:22:23.761(1)? (STDERR) 
W20150410-13:22:23.761(1)? (STDERR) events.js:72
W20150410-13:22:23.761(1)? (STDERR)         throw er; // Unhandled 'error' event
W20150410-13:22:23.761(1)? (STDERR)               ^
W20150410-13:22:23.771(1)? (STDERR) Error: write after end
W20150410-13:22:23.771(1)? (STDERR)     at writeAfterEnd (_stream_writable.js:133:12)
W20150410-13:22:23.771(1)? (STDERR)     at Gzip.Writable.write (_stream_writable.js:181:5)
W20150410-13:22:23.771(1)? (STDERR)     at ServerResponse.res.write (/Users/ecolby/.meteor/packages/webapp/.1.2.0.h5frgv++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:109:18)
W20150410-13:22:23.771(1)? (STDERR)     at ServerResponse.res.end (/Users/ecolby/.meteor/packages/webapp/.1.2.0.h5frgv++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:116:14)
W20150410-13:22:23.771(1)? (STDERR)     at sendResponseIfDone (packages/cfs:http-methods/http.methods.server.api.js:543:1)
W20150410-13:22:23.771(1)? (STDERR)     at IncomingMessage.<anonymous> (packages/cfs:http-methods/http.methods.server.api.js:568:1)
W20150410-13:22:23.771(1)? (STDERR)     at IncomingMessage.emit (events.js:92:17)
W20150410-13:22:23.771(1)? (STDERR)     at _stream_readable.js:944:16
W20150410-13:22:23.771(1)? (STDERR)     at process._tickCallback (node.js:442:13)
=> Exited with code: 8

![test3](https://cloud.githubusercontent.com/assets/11865800/7087484/da40f744-df83-11e4-925b-e58741c4e658.png)

**Comment by aldeed** [comment]
This might be the result of my changes in https://github.com/CollectionFS/Meteor-http-methods/commit/d2985c4a5823e66b84f4c545c807eefb8e6064c5

I saw this error once while testing it, but I couldn't reproduce it reliably. There must be an issue with my logic (response.end before streaming is done), but I'm not sure how to fix this and also keep my fix.

If someone can provide a simple app repo and instructions to consistently reproduce, it will be easier to fix.

@raix

**Comment by friendtogeoff** [comment]
Hi, I've just cut a (simplest possible?) meteor app that reproduces this issue at friendtogeoff/collectionfstest.

There's a choose file button.

Choosing the included test3.png results in the image being correctly rendered in the placeholder.

Choosing the included test3.svg causes the server to crash.

@friendtogeoff

**Comment by dr-dimitru** [comment]
@aldeed I've rolled back to previous version still get the same error described in #650

**Comment by friendtogeoff** [comment]
@dr-dimitru I've tried rolling back cfs:standard-packages and cfs:grids as far back as possible and neither helped - the server crashes are still there.

I do have a previous built version of my app in production which had older versions of cfs:standard-packages and cfs:gridfs and does work correctly. This leads me to believe that the problem maybe caused by a new revision of one of @aldeed's dependencies causing his code to be less stable. I've not yet managed to work out which this could be.

**Comment by dr-dimitru** [comment]
@friendtogeoff could you please mention version of old `cfs:standard-packages` package which stable on your end? Or share it somewhere, so I'll link it as local package

**Comment by friendtogeoff** [comment]
@dr-dimitru, I'm sorry, but I messed up with that.

The version of the App that is working was built before I had the code base under proper version control. I'm not quite clever enough to work out how to find the package versions from the as built node App.

It is probable that it was also built before the recent Meteor update.

I'm also not convinced that simply having the old version of the cfs:standard-packages will fix your problem. I tried reverting cfs:standard-packages to a version committed well before I built the working version of my App. That didn't fix things - hence I think that the trigger for the issue is a change in another package that CollectionFS depends upon.

**Comment by dr-dimitru** [comment]
@friendtogeoff but older version suppose to have older versions of dependencies, as usually version mentioned in dependencies

**Comment by friendtogeoff** [comment]
It appears that SendResponseIfDone() is called twice - and by the comments it appears that this is deliberate. Once through the request 'end' event handler (568) and once through the method call itself (615).

Commenting out the call in the 'end' handler stops the server crashing (but probably ends up leaving connections open). I wonder whether the client is ending the requests early, thereby triggering a close on the response before the response has been fully drained down? Commenting out the call in the 'end' handler prevents an early request close from triggering an early response close...

**Comment by aldeed** [comment]
@friendtogeoff, it's possible that we need to wait for some third event other than done and 'end' before we call response.end(), but I'm not sure what it would be. It seems like we're ending the response but there is still a stream emptying somewhere.

Also, since the pkg is a dependency of a dependency, reverting the standard-packages may not actually revert this package. A better check to see if it was due to my change would be to add `cfs:http-methods@=0.0.27` to your .meteor/packages file. If the error goes away, then it's due to my commit, which it probably is.

**Comment by friendtogeoff** [comment]
@aldeed, yes, agreed re. third event - though I'm not really familiar enough with Node's http stack yet to say where to go looking.

Simple test of reverting to cfs:http-methods@=0.0.27 makes the test app run smoothly :-). As you would expect it does force some reversions across the cfs package suite.

I don't think that my hack is the right answer - in testing I think that I've seen it fail to update the picture on client side following upload.

**Comment by YannLeBihan** [comment]
Hi all,

Thank you so much for this thread. Applying the patch to my Meteor packages file instantly solved the server crashes I had been experimenting for a few days with SVG urls.

**Comment by dr-dimitru** [comment]
Thank you all for responses.

But we're stuck with this package, also it's dramatically slow down our app, doesn't support non-latin symbols in filename and has limits on big files upload/download.

We spent two weeks for research and create our own package: [Meteor-Files][1]. It's sleek and easy to use. Your hands is untied, you're free to do anything with uploaded file(s), modify, resize images, even store to GridFS if you wish so.

We're hope our package will help to solve simple task as upload/download files to other developers. Meteorites unite!

  [1]: https://github.com/VeliovGroup/Meteor-Files/

**Comment by acemtp** [comment]
I also have this issue with .svg only.

forcing the package version  cfs:http-methods@=0.0.27 fixed the issue.

This bug happen every time I refresh the client on a page that display a .svg file (uploaded with cfs)

**Comment by oorabona** [comment]
Hello!

I came across this same issue and it appears that changing condition on line [541](https://github.com/CollectionFS/Meteor-http-methods/blob/master/http.methods.server.api.js#L541) from ```self.done``` to ```self.finished``` fixes the issue.

FWIW

**Comment by tehXor** [comment]
I came across an issue which looked very much like the here referenced https://github.com/CollectionFS/Meteor-http-methods/issues/39 every time a user would download a file. The download goes through, however afterwards after the error the Meteor server restarts which is a absolute no go of course.
My files also nearly always contain JSON strings but I'm not sure if that has something to do with the error.

In any case @oorabona 's solution seems to fix the problem (thanks a lot!). It would be great if someone could verify this and push it in the next stable release as well.

**Comment by iSuslov** [comment]
This is critical! Are you guys going to do something with this?

**Comment by YannLeBihan** [comment]
Hi,

Is it safe now to upgrade every part of CollectionFS to its most recent release, or should we keep on with a patched version ?

**Comment by YannLeBihan** [comment]
OK... 15 days of daily use later, I can confirm that all problems with SVG files have disappeared here. Thanks a lot for this fix !

**Comment by oorabona** [comment]
@YannLeBihan, @tehXor : thanks for your feedback ! :smile:
Great that it still works with all the changes that came along Meteor 1.2.

**Comment by chansdad** [comment]
Upgraded from meteor 1.1.0.3 to 1.2.1 , seeing the issue  right after a jpg file is uploaded from the ios app . and then server just crashes and does not respond . Have to restart meteor . forcing the package version cfs:http-methods@=0.0.27 did not solve the issue . Any suggestions??

=> Couldn't spawn process: channel closed
=> Client modified -- refreshing


This is a serious error considering meteor server just crashes . Any help or suggestions would be greatly appreciated.
