### ISSUE TITLE
Server crash when downloading JSON data.

### ISSUE THREAD

**Issue by darxtar2005** [CollectionFS/Meteor-CollectionFS#664]
Upload is going fine but download crashes the server and forces restart.
I tried cfs:filesystem and cfs:grifs, both have the same error when handling JSON files.

Write after end error:
W20150424-00:12:25.867(1)? (STDERR) 
W20150424-00:12:25.867(1)? (STDERR) events.js:72
W20150424-00:12:25.867(1)? (STDERR)         throw er; // Unhandled 'error' event
W20150424-00:12:25.867(1)? (STDERR)               ^
W20150424-00:12:25.876(1)? (STDERR) Error: write after end
W20150424-00:12:25.876(1)? (STDERR)     at writeAfterEnd (_stream_writable.js:133:12)
W20150424-00:12:25.877(1)? (STDERR)     at Gzip.Writable.write (_stream_writable.js:181:5)
W20150424-00:12:25.877(1)? (STDERR)     at ServerResponse.res.write (/home/alex/.meteor/packages/webapp/.1.2.0.soszxr++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:109:18)
W20150424-00:12:25.877(1)? (STDERR)     at ServerResponse.res.end (/home/alex/.meteor/packages/webapp/.1.2.0.soszxr++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:116:14)
W20150424-00:12:25.877(1)? (STDERR)     at sendResponseIfDone (packages/cfs:http-methods/http.methods.server.api.js:543:1)
W20150424-00:12:25.877(1)? (STDERR)     at IncomingMessage.<anonymous> (packages/cfs:http-methods/http.methods.server.api.js:568:1)
W20150424-00:12:25.877(1)? (STDERR)     at IncomingMessage.emit (events.js:92:17)
W20150424-00:12:25.877(1)? (STDERR)     at _stream_readable.js:944:16
W20150424-00:12:25.877(1)? (STDERR)     at process._tickCallback (node.js:442:13)

Behaviour seems similar to:
Server crash on retrieval of SVG data #648 

Meteor list:
accounts-password             1.1.1  
accounts-ui                   1.1.5  
alanning:roles                1.2.13  
aldeed:autoform               5.1.2  
anti:fake                     0.4.1  
cfs:gridfs                    0.0.33  
cfs:standard-packages         0.5.8  
cmather:handlebars-server     0.2.0* 
coffeescript                  1.0.6  
cunneen:mailgun               0.9.1  
dburles:collection-helpers    1.0.3  
dburles:factory               0.3.9  
email                         1.0.6  
fuatsengul:iron-router-auth   1.0.7 
iron:router                   1.0.7  
joshowens:accounts-entry      1.0.3  
joshowens:simple-form         0.2.2 
jquery                        1.11.3_2  
less                          1.0.14  
manuelschoebel:ms-seo         0.4.1 
matb33:collection-hooks       0.7.13  
meteor-platform               1.2.2  
meteorhacks:zones             1.4.0 
mrt:fullcalendar              1.6.1  
mrt:jquery-ui                 1.9.2 
mrt:moment                    2.8.1 
mrt:underscore-string-latest  2.3.3 
reywood:publish-composite     1.3.6  
zimme:iron-router-active      1.0.4

**Comment by markclayton** [comment]
I'm literally having the same problem. I'm using `cfs:filesystem` and `cfs:standard-packages` to handle my upload/download. Upload works perfectly, however it crashes on download when using the following handlebar `{{url download=true}}`. I'm literally following the exact same code in this tutorial - https://www.youtube.com/watch?v=vo-2OPje0V4 . So strange. Please help anyone.

**Comment by markclayton** [comment]
My stack trace is the exact same as well.

**Comment by dpacmittal** [comment]
I have the exact same issue, and exact same stack trace as well. I'm using `cfs:gridfs` and `cfs:standard-packages`.

**Comment by ameesters** [comment]
Any update on this issue? I have the problem as well:
```
=> App running at: http://localhost:3000/
W20150820-10:03:22.209(2)? (STDERR) 
W20150820-10:03:22.211(2)? (STDERR) events.js:72
W20150820-10:03:22.211(2)? (STDERR)         throw er; // Unhandled 'error' event
W20150820-10:03:22.211(2)? (STDERR)               ^
W20150820-10:03:22.211(2)? (STDERR) Error: write after end
W20150820-10:03:22.211(2)? (STDERR)     at writeAfterEnd (_stream_writable.js:133:12)
W20150820-10:03:22.212(2)? (STDERR)     at Gzip.Writable.write (_stream_writable.js:181:5)
W20150820-10:03:22.212(2)? (STDERR)     at ServerResponse.res.write (/home/alexander/.meteor/packages/webapp/.1.2.0.1x0et1m++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:109:18)
W20150820-10:03:22.212(2)? (STDERR)     at ServerResponse.res.end (/home/alexander/.meteor/packages/webapp/.1.2.0.1x0et1m++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:116:14)
W20150820-10:03:22.212(2)? (STDERR)     at sendResponseIfDone (packages/cfs:http-methods/http.methods.server.api.js:542:1)
W20150820-10:03:22.212(2)? (STDERR)     at IncomingMessage.<anonymous> (packages/cfs:http-methods/http.methods.server.api.js:567:1)
W20150820-10:03:22.212(2)? (STDERR)     at IncomingMessage.emit (events.js:92:17)
W20150820-10:03:22.213(2)? (STDERR)     at _stream_readable.js:944:16
W20150820-10:03:22.213(2)? (STDERR)     at process._tickCallback (node.js:442:13)
=> Exited with code: 8
=> Meteor server restarted
```

**Comment by markclayton** [comment]
Hey guys, so I fixed this issue awhile back (at least in my scenario) but forgot to post it. Unfortunately I'm new to meteor and don't really have to much information as to the root cause of this issue. All I know is that I was able to successfully download files using the following:

`<a class="btn btn-primary" href="{{this.url download=true}}" target="_parent">Download</a>`

There is something about the `target="_parent"`attribute that fixes the issue. Looking around and you'll see similar solutions. Hope this helps guys!

**Comment by aldeed** [comment]
I released a fix in 0.0.30. Please add `cfs:http-methods@0.0.30` to your app to ensure it's using this version and see if that fixes your issues.
