### ISSUE TITLE
Pipe to tempstore fails for unknown reason

### ISSUE THREAD

**Issue by bryantebeek** [CollectionFS/Meteor-CollectionFS#668]
We see the following error when trying to insert an image using a uri:

```
error:  Error: You cannot pipe after data has been emitted from the response.
    at Request.pipe (/mnt/data/2/node_modules/request/request.js:1608:13)
    at beginStorage (packages/cfs:collection/api.common.js:32:1)
    at checkAndInsert (packages/cfs:collection/api.common.js:68:1)
    at EventEmitter.FS.Collection.insert (packages/cfs:collection/api.common.js:75:1)
    at packages/partup:server-base/accounts.js:30:1
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:999:1)
    at Object.Accounts.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1164:1)
    at Object.updateOrCreateUserFromExternalService (packages/splendido:accounts-meld/lib/accounts-meld-server.js:635:1)
    at [object Object].Package (packages/accounts-oauth/oauth_server.js:45:1)
    at packages/accounts-base/accounts_server.js:358:1
```

The collection looks like this:

```
if (Meteor.isServer) {
    stores.push(new FS.Store.S3('original', {
        bucket: process.env.AWS_BUCKET_NAME,
        region: process.env.AWS_BUCKET_REGION
    }));

    stores.push(new FS.Store.S3('1200x520', {
        bucket: process.env.AWS_BUCKET_NAME,
        region: process.env.AWS_BUCKET_REGION,
        // transformWrite: function (image, readStream, writeStream) {
        //     gm(readStream, image.name()).resize(1200, 520).stream().pipe(writeStream);
        // }
    }));

    stores.push(new FS.Store.S3('360x360', {
        bucket: process.env.AWS_BUCKET_NAME,
        region: process.env.AWS_BUCKET_REGION,
        // transformWrite: function (image, readStream, writeStream) {
        //     gm(readStream, image.name()).resize(360, 360).stream().pipe(writeStream);
        // }
    }));
} else {
    stores.push(new FS.Store.S3('original'));
    stores.push(new FS.Store.S3('1200x520'));
    stores.push(new FS.Store.S3('360x360'));
}
```

Any help would be much appreciated, we have been struggling with the issue for a while now!

**Comment by rhyslbw** [comment]
Probably going to need more context. A reproduction repo will be best
