### ISSUE TITLE
Problems with audio player. Error: Can't render headers after they are sent to the client.

### ISSUE THREAD

**Issue by Praxie** [CollectionFS/Meteor-CollectionFS#707]
Hello. I'm working on the audio player for meter. I use the s3 storage to store audio files.
While playing an audio file I get some strange random error that crashes server:
```
http.js:732
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:732:11)
    at ServerResponse.writeHead (http.js:1153:20)
    at ProxyServer.<anonymous> (/Users/mike/.meteor/packages/meteor-tool/.1.1.3.y8k213++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-proxy.js:96:21)
    at ProxyServer.emit (/Users/mike/.meteor/packages/meteor-tool/.1.1.3.y8k213++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/Users/mike/.meteor/packages/meteor-tool/.1.1.3.y8k213++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
    at ClientRequest.emit (events.js:117:20)
    at Socket.socketOnData (http.js:1593:9)
    at TCP.onread (net.js:528:27)
```

Is it possible to get the direct s3 link?

**Comment by Praxie** [comment]
Actually, this error happens when I try to change the currentTime property of audio element.

**Comment by rhyslbw** [comment]
For accessing the file directly check this https://github.com/CollectionFS/Meteor-CollectionFS/issues/610#issuecomment-82195682

**Comment by Praxie** [comment]
I'm talking about something like this: 'https://s3.amazonaws.com/bucket/folder/track.mp3'
Because this problem is caused by the access-point package I think.

**Comment by rhyslbw** [comment]
Right. Raix was pointing out you should be able to build a link using fileKey if the file is public

**Comment by Praxie** [comment]
Thanks @rhyslbw. Do you have any idea how to fix that issue without changing url?

**Comment by rhyslbw** [comment]
Sorry I don't

**Comment by jimmiebtlr** [comment]
I'm getting this error fairly consistently.  At first glance it seems like it may be something along the lines of requesting a file while it is still in the upload process.
