### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by hluz** [CollectionFS/Meteor-CollectionFS#725]
I am getting a server crash with the following console error:

```
/var/nodeapps/isforms/bundle/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'keys' of undefined
    at packages/cfs:tempstore/tempStore.js:297:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
error: Forever detected script exited with code: 8
```

I believe it is caused by file uploads. Any ideas on how to determine what causes it? Servers bouncing and being off-line for some period of time is no good at all...

**Comment by hluz** [comment]
Help anyone? please...

**Comment by nathantsoi** [comment]
same here. any ideas @raix, @aldeed or @rhyslbw?

**Comment by migloo** [comment]
Same here.
/opt/meteor/app/programs/server/node_modules/fibers/future.js:24
5
                                                throw(ex);
                                                      ^
TypeError: Cannot read property 'keys' of undefined
    at packages/cfs:tempstore/tempStore.js:297:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
error: Forever detected script exited with code: 8
error: Script restart attempt #3

Would anyone be able to point me in the right direction? 
Thank you,

**Comment by nathantsoi** [comment]
if i recall correctly, we were trying to read a key (cookie name) that didnt exist from meteor-server-cookies. it was happening around the same time that this was fixed, but i dont think they were related: https://github.com/gfk-ba/meteor-server-cookies/pull/3

**Comment by ChrisCinelli** [comment]
I see it too. This crash our server =/
Not sure what happened here: https://github.com/CollectionFS/Meteor-CollectionFS/blob/b46cb20d2d86a806e19e9ffbd72955c2a4ae37e7/packages/tempstore/tempStore.js#L297

**Comment by ChrisCinelli** [comment]
@aldeed Any idea what can cause this?

**Comment by ChrisCinelli** [comment]
This is obviously related with #619

**Comment by iSuslov** [comment]
same for me. Critical

**Comment by ChrisCinelli** [comment]
Who is supposed to solve this? Or can somebody give us a hint?

**Comment by hluz** [comment]
https://forums.meteor.com/t/deprecating-collectionfs/16921

**Comment by ChrisCinelli** [comment]
@hluz, @nathantsoi and @migloo 
Did you ever solve this?

**Comment by hluz** [comment]
I moved away from CollectionFS to vsivsi:file-collection (I only needed GridFS support)

**Comment by Buom01** [comment]
It happend to me when I add-remove-add-remove fastly an image that have multiple storages and transformations, and because there are no way to stop uploading when removing, the best idea is to say goodbye to CollectionFS

**Comment by mngkvn** [comment]
I guess I have to agree with @Buom01 , Aside from this issue, there are some other issues and it seems like they don't have the time to do fix it anymore as some of them were still hanging for 1 year now.
