### ISSUE TITLE
Crashing server due to ImageMagick - could not get it going again until I deleted temp chunks

### ISSUE THREAD

**Issue by adamgins** [CollectionFS/Meteor-CollectionFS#732]
Hi, I had an issue with an image that ImageMagick did not like. It seemed to crash my entire server.

I ended up deleteing the offending file from `cfs._tempstore.chunks`... sorry I could not work out how else to stop it crashing.

My code:

```
stores: [
        new FS.Store.S3("largeImages", {
            //region: "s3-us-west-2.amazonaws.com", //optional in most cases
            accessKeyId: "mykey", //required if environment variables are not set
            secretAccessKey: "mysecret", //required if environment variables are not set
            bucket: "mybucket", //required
            ACL: "public-read-write", //optional, default is 'private', but you can allow public or secure access routed through your app URL
            beforeWrite: function (fileObj) {
                return {
                    name: 'large_' + fileObj.name()

                };
            },
            // The rest are generic store options supported by all storage adapters
            //transformWrite: myTransformWriteFunction, //optional
            // transformRead: myTransformReadFunction, //optional
            // maxTries: 1 //optional, default 5
            transformWrite: function(fileObj, readStream, writeStream) {
                try{
                    // Transform the image into a 10x10px thumbnail
                    console.log("creating image1600:" +  fileObj.name());
                    gm(readStream, fileObj.name()).resize('1600').autoOrient().stream().pipe(writeStream);
                } catch(err){
                    throwError(err)
                }

            }
        }),
```
I then have similar transforms.

One the console I saw 
```
  throw er; // Unhandled 'error' event 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:  gm identify: Request did not return an image. 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:  events.js:72 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:  Error: Command failed: ICC Profile CS 52474220 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:      at ChildProcess._spawn.proc.on.onExit (/built_app/programs/server/npm/cfs_graphicsmagick/node_modules/gm/lib/command.js:279:17) 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:  gm identify: Missing a required image channel (/tmp/gmEzXvlN). 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:      at maybeClose (child_process.js:766:16) 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:      at Socket.emit (events.js:95:17) 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:      at ChildProcess.emit (events.js:98:17) 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:      at Pipe.close (net.js:466:12) 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:                ^ 
Jul 02 13:41:49 Buzzy-Docker-buzzy1 buzzy:      at Socket.<anonymous> (child_process.js:979:11) 
```

How should I be catering for these types of issues so they don't bring the whole thing down a heap?

#227

**Comment by adamgins** [comment]
@aldeed @raix wondering if you have any input please. ie would an 'onInvalid' function capture this? or is there some call back I can put in the  `.pipe().stream()` work here? Just not sure where the error is generating. 

BTW, this does not seem to show up when running on my local dev machine... only on my AWS environment.

Any help appreciated
