### ISSUE TITLE
images not showing

### ISSUE THREAD

**Issue by tom12e** [CollectionFS/Meteor-CollectionFS#734]
I am trying to show my uploaded images, they dont show up and when I try to open the URL I get this error:

```
      
Error in method "/cfs/files/:value/:value/:value/", Error: Error: start must be <= end
    at new ReadStream (fs.js:1489:13)
    at Object.fs.createReadStream (fs.js:1450:10)
    at Object.FS.StorageAdapter.createReadStream (packages/cfs:filesystem/filesystem.server.js:59:1)
    at Object.self.adapter.createReadStreamForFileKey (packages/cfs:storage-adapter/storageAdapter.server.js:75:1)
    at [object Object].FS.Transform.createReadStream (packages/cfs:storage-adapter/transform.server.js:97:1)
    at Object.self.adapter.createReadStream (packages/cfs:storage-adapter/storageAdapter.server.js:85:1)
    at Object.httpGetHandler (packages/cfs:access-point/access-point-handlers.js:208:1)
    at Object.accessPoint.get (packages/cfs:access-point/access-point-server.js:175:1)
    at packages/cfs:http-methods/http.methods.server.api.js:575:1
        
```

**Comment by sakshi-kataria** [comment]
PLease define why this error is coming

**Comment by jeanfredrik** [comment]
@tom12e Did you find a solution for this error?

**Comment by kenshinman** [comment]
Hello @tom12e , Did you find a solution to this issue? if yes, please share. Thanks

**Comment by zhe1ka** [comment]
+1
