### ISSUE TITLE
transformWrite crashes my app

### ISSUE THREAD

**Issue by abcd-ca** [CollectionFS/Meteor-CollectionFS#776]
My app is crashing whenever I do anything with `stream()` in my `transformWrite` function. I'm just following the example from [step 20 of the Meteor-Angular tutorial](http://angular-meteor.com/tutorials/angular1/handling-files-with-collectionfs). I'm working locally and have only imagemagick installed using brew on OS X. I also tried having graphicsmagick installed and also ONLY graphicsmagick. I'm back to only imagemagick because that's what the host, Modulus.io has.  

The server just keeps rebooting after the crash. I've tried doing the `stream()` as a function with and without a callback but that doesn't seem to matter. Please advise, thank you.

Here is my code:

```
var DataImages, dataImageLargeStoreConfig, dataImageThumbStoreConfig, dataImagesStoreLarge, dataImagesStoreThumb;

if (gm.isAvailable) {
  console.log('gm is available');
} else {
  console.log('Error: gm is not available');
}

dataImageLargeStoreConfig = {};

dataImageThumbStoreConfig = {
//this transformWrite implementation is directly from the Angular Meteor tutorial.
  transformWrite: function(fileObj, readStream, writeStream) {
    console.log('transformWrite');
    gm(readStream, fileObj.name()).resize('50', '50').stream().pipe(writeStream);
  },
};

dataImagesStoreLarge = new FS.Store.GridFS('dataImagesLarge', dataImageLargeStoreConfig);
dataImagesStoreThumb = new FS.Store.GridFS('dataImagesThumb', dataImageThumbStoreConfig);

DataImages = new FS.Collection('dataImages', {
  stores: [dataImagesStoreLarge, dataImagesStoreThumb],
  filter: {
    allow: {
      contentTypes: ['image/*']
    }
  }
});

DataImages.allow({
  insert: function(userId) {
    if (userId) {
      return true;
    } else {
      return false;
    }
  },
  remove: function(userId) {
    if (userId) {
      return true;
    } else {
      return false;
    }
  },
  download: function() {
    return true;
  },
  update: function(userId) {
    if (userId) {
      return true;
    } else {
      return false;
    }
  }
});

Meteor.publish('dataImages', function() {
  return DataImages.find({});
});

```

This results in the following:

```
I20150807-16:22:25.877(-7)? gm is available   
I20150807-16:22:25.879(-7)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
I20150807-16:22:25.879(-7)? transformWrite
W20150807-16:22:26.016(-7)? (STDERR) 
W20150807-16:22:26.017(-7)? (STDERR) events.js:72
W20150807-16:22:26.017(-7)? (STDERR)         throw er; // Unhandled 'error' event
W20150807-16:22:26.017(-7)? (STDERR)               ^
W20150807-16:22:26.018(-7)? (STDERR) Error: write EPIPE
W20150807-16:22:26.018(-7)? (STDERR)     at errnoException (net.js:905:11)
W20150807-16:22:26.018(-7)? (STDERR)     at Object.afterWrite (net.js:721:19)
```

**Comment by abcd-ca** [comment]
I don't know why brew didn't work – maybe imagemagick or its libs weren't in my path but in the end I uninstalled via brew and installed a binary from here, http://www.imagemagick.org/script/binary-releases.php#macosx. I no longer get the crashing error and am now only troubleshooting why my thumbnail shows as a broken image but hopefully that's unrelated and easily solved.
