### ISSUE TITLE
How to get an URL for a file that has been uploaded as a base64-String?

### ISSUE THREAD

**Issue by derwaldgeist** [CollectionFS/Meteor-CollectionFS#803]
My use case: I'm using the mdg:camera package to get an image from my mobile device. This image is returned as  a standard base64-String that could be used directly in an image's src attribute.

For performance reasons, I would like to retrieve the image from GridFS using an HTTP URL instead. The upload is working fine, but if I'm retrieving the image and call .url() on the returned File object, the URL is null. I assumed the URL would be set automatically, if no file name is given. Obviously, this is not the case.

Is there a way to convert the base64 string in a valid File object and upload it as such instead?

**Comment by derwaldgeist** [comment]
I now opened the URL that is returned by .url({ brokenIsFine: true }) in the browser. Here one can see an error message:

```js
Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'images' of undefined
    at Object.httpGetHandler (packages/cfs:access-point/access-point-handlers.js:61:1)
    at Object.accessPoint.get (packages/cfs:access-point/access-point-server.js:175:1)
    at packages/cfs:http-methods/http.methods.server.api.js:575:1
```

**Comment by derwaldgeist** [comment]
After inspecting the database collections, I found out that the file content was never saved to the GridFS collection, if it was uploaded as base64. There is only a file record in cfs.images.filerecord, but no record in cfs_gridfs.images.files. It is quite obvious that this way of uploading a file is broken.

**Comment by derwaldgeist** [comment]
Since there was no feedback so far, I switched over to Slingshot, although that package is not optimal for my use-case. But at least the upload worked there. Still hoping that CollectionFS/GridFS will support this scenario at some time.

**Comment by AlexFrazer** [comment]
You want to insert as base 64 string? I managed to do this as so:

```
Meteor.methods({
  'uploadImage': function (base64EncodedImage) {
    let future = new Future();
    let onComplete = future.resolver();
    let fsFile = new FS.File();
    fsFile.attachData(base64EncodedImage, function(error) {
      if (error) resolve(error, null);
      QAImages.insert(fsFile, onComplete);
    });
    return future.wait();
});

```
