### ISSUE TITLE
Random problem with insert on S3

### ISSUE THREAD

**Issue by ChrisCinelli** [CollectionFS/Meteor-CollectionFS#824]
Sporadically I get these errors:

    [Wed Sep 30 2015 15:25:32 GMT+0000 (UTC)] INFO Exception in callback of async function: Error: failed [403]
    at Object.Future.wait (/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:398:15)
    at Object.call (packages/meteor/helpers.js:119:1)
    at [object Object].Meteor.methods._cfs_getUrlInfo (packages/cfs:file/fsFile-server.js:186:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:1530:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
    at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
    at EventEmitter.fsFileAttachData [as attachData] (packages/cfs:file/fsFile-common.js:77:1)
    at EventEmitter.FS.File (packages/cfs:file/fsFile-common.js:17:1)
    at EventEmitter.FS.Collection.insert (packages/cfs:collection/api.common.js:79:1)
    at app/server/methods.js:151:24

The code at 151 is: 
                Images.insert(data.image, function (err, fileObj) {
                  data.image2 = fileObj._id;
                  done();
                });

**Comment by ChrisCinelli** [comment]
Looking at:
It looks like the problem is that the HTTP.call does not have a `try/catch`.
According to Meteor documentation: https://github.com/CollectionFS/Meteor-CollectionFS/blob/f28a3fcbfe86b999fcb2896363134fa9753d152e/packages/file/fsFile-server.js#L186
*This function initiates an HTTP request to a remote server.*

*On the server, this function can be run either synchronously or asynchronously. If the callback is omitted, it runs synchronously and the results are returned once the request completes successfully. If the request was not successful, an error is thrown.* 

Solution: Retry -- See: https://meteorhacks.com/how-to-use-the-new-meteor-retry-package
