### ISSUE TITLE
As soon as I create a new FS.Collection, my app crash throwing a `MongoError: auth failed`

### ISSUE THREAD

**Issue by THPubs** [CollectionFS/Meteor-CollectionFS#874]
Im using a local Mongo server and have connected my meteor app to it using `MONGO_URL` environment variable. But as soon as I create a FS collection like this :

    Images = new FS.Collection("images", {
        mongoUrl: "mongodb://leafycode:jHArfRHaJDB7mHxuv8vnKD9AKaxtRE8GNTFfv4h@127.0.0.1:27017/mmw",
        stores: [new FS.Store.GridFS("images", {})]
    });

I get the following error. I even tried without passing `mongoUrl` to Fs.Collection. I use `cfs:gridfs`. How can I fix this?

    => Started proxy.                             
    I20151202-16:13:03.111(5.5)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
    W20151202-16:13:03.112(5.5)? (STDERR) 
    W20151202-16:13:03.112(5.5)? (STDERR) /home/pubudu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
    W20151202-16:13:03.112(5.5)? (STDERR) 						throw(ex);
    W20151202-16:13:03.112(5.5)? (STDERR) 						      ^
    W20151202-16:13:03.112(5.5)? (STDERR) MongoError: auth failed
    W20151202-16:13:03.112(5.5)? (STDERR)     at Object.Future.wait (/home/pubudu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    W20151202-16:13:03.112(5.5)? (STDERR)     at packages/meteor/helpers.js:119:1
    W20151202-16:13:03.112(5.5)? (STDERR)     at new FS.StorageAdapter (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:255:1)
    W20151202-16:13:03.112(5.5)? (STDERR)     at new FS.Store.GridFS (packages/cfs_gridfs/packages/cfs_gridfs.js:54:1)
    W20151202-16:13:03.112(5.5)? (STDERR)     at lib/collections/Images.js:3:14
    W20151202-16:13:03.112(5.5)? (STDERR)     at lib/collections/Images.js:4:4
    W20151202-16:13:03.113(5.5)? (STDERR)     at /home/pubudu/Projects/MMW-Admin/.meteor/local/build/programs/server/boot.js:242:10
    W20151202-16:13:03.113(5.5)? (STDERR)     at Array.forEach (native)
    W20151202-16:13:03.113(5.5)? (STDERR)     at Function._.each._.forEach (/home/pubudu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    W20151202-16:13:03.113(5.5)? (STDERR)     at /home/pubudu/Projects/MMW-Admin/.meteor/local/build/programs/server/boot.js:137:5
    W20151202-16:13:03.113(5.5)? (STDERR)     - - - - -
    W20151202-16:13:03.113(5.5)? (STDERR)     at Object.toError (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    W20151202-16:13:03.113(5.5)? (STDERR)     at /home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/auth/mongodb_cr.js:39:33
    W20151202-16:13:03.113(5.5)? (STDERR)     at /home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1806:9
    W20151202-16:13:03.113(5.5)? (STDERR)     at Server.Base._callHandler (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    W20151202-16:13:03.113(5.5)? (STDERR)     at /home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    W20151202-16:13:03.113(5.5)? (STDERR)     at [object Object].MongoReply.parseBody (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    W20151202-16:13:03.113(5.5)? (STDERR)     at [object Object].<anonymous> (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    W20151202-16:13:03.113(5.5)? (STDERR)     at [object Object].emit (events.js:95:17)
    W20151202-16:13:03.113(5.5)? (STDERR)     at [object Object].<anonymous> (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    W20151202-16:13:03.113(5.5)? (STDERR)     at [object Object].emit (events.js:98:17)
    => Exited with code: 8
    I20151202-16:13:07.530(5.5)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
    W20151202-16:13:07.545(5.5)? (STDERR) 
    W20151202-16:13:07.545(5.5)? (STDERR) /home/pubudu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
    W20151202-16:13:07.545(5.5)? (STDERR) 						throw(ex);
    W20151202-16:13:07.546(5.5)? (STDERR) 						      ^
    W20151202-16:13:07.565(5.5)? (STDERR) MongoError: auth failed
    W20151202-16:13:07.566(5.5)? (STDERR)     at Object.Future.wait (/home/pubudu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    W20151202-16:13:07.566(5.5)? (STDERR)     at packages/meteor/helpers.js:119:1
    W20151202-16:13:07.566(5.5)? (STDERR)     at new FS.StorageAdapter (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:255:1)
    W20151202-16:13:07.566(5.5)? (STDERR)     at new FS.Store.GridFS (packages/cfs_gridfs/packages/cfs_gridfs.js:54:1)
    W20151202-16:13:07.566(5.5)? (STDERR)     at lib/collections/Images.js:3:14
    W20151202-16:13:07.566(5.5)? (STDERR)     at lib/collections/Images.js:4:4
    W20151202-16:13:07.566(5.5)? (STDERR)     at /home/pubudu/Projects/MMW-Admin/.meteor/local/build/programs/server/boot.js:242:10
    W20151202-16:13:07.566(5.5)? (STDERR)     at Array.forEach (native)
    W20151202-16:13:07.566(5.5)? (STDERR)     at Function._.each._.forEach (/home/pubudu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    W20151202-16:13:07.566(5.5)? (STDERR)     at /home/pubudu/Projects/MMW-Admin/.meteor/local/build/programs/server/boot.js:137:5
    W20151202-16:13:07.566(5.5)? (STDERR)     - - - - -
    W20151202-16:13:07.567(5.5)? (STDERR)     at Object.toError (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    W20151202-16:13:07.567(5.5)? (STDERR)     at /home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/auth/mongodb_cr.js:39:33
    W20151202-16:13:07.567(5.5)? (STDERR)     at /home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1806:9
    W20151202-16:13:07.567(5.5)? (STDERR)     at Server.Base._callHandler (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    W20151202-16:13:07.567(5.5)? (STDERR)     at /home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    W20151202-16:13:07.567(5.5)? (STDERR)     at [object Object].MongoReply.parseBody (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    W20151202-16:13:07.567(5.5)? (STDERR)     at [object Object].<anonymous> (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    W20151202-16:13:07.567(5.5)? (STDERR)     at [object Object].emit (events.js:95:17)
    W20151202-16:13:07.567(5.5)? (STDERR)     at [object Object].<anonymous> (/home/pubudu/.meteor/packages/cfs_gridfs/.0.0.29.19tlqvt++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    W20151202-16:13:07.567(5.5)? (STDERR)     at [object Object].emit (events.js:98:17)

**Comment by THPubs** [comment]
Just fixed this by adding the mongo url without a user.
