### ISSUE TITLE
Exception in callback of async function: Error: You cannot pipe after the response has been ended.

### ISSUE THREAD

**Issue by javascriptlove** [CollectionFS/Meteor-CollectionFS#920]
I'm getting this error sometimes (Meteor 1.2.1 on mac), when adding the file through url, like this

```
var file = new FS.File(url);
var mediaInsert = Meteor.wrapAsync(function(file, callback) {
        Files.insert(file, function(err, fileObj) {
            // set filename to _id
            file.name(file._id);

            callback && callback(err, fileObj);
        });
    });
    var fileObj = mediaInsert(file);

// wait for downloading
    while (getFileStatus(fileObj._id) != 'valid') {
        Meteor._sleepForMs(200);
    }
```

This piece of code runs in a Meteor.call and returns the _id of the new file. Additionally, i check whether the file is already downloaded and only then return the _id.

So i guess something creates a stream and then i return and there are other streams still somewhere.. 

CFS-related package versions:

```
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:filesystem@0.1.2
cfs:http-methods@0.0.30
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.3
cfs:tempstore@0.1.5
cfs:upload-http@0.0.20
cfs:worker@0.1.4
```

The full exception here:

```
I20160129-16:02:06.655(1)?     at Request.pipe (/Users/akuzmenok/.meteor/packages/cfs_data-man/.0.0.6.d6atck++os+web.browser+web.cordova/npm/node_modules/request/request.js:1726:13)
I20160129-16:02:06.655(1)?     at beginStorage (meteor://💻app/packages/cfs_collection/packages/cfs_collection.js:220:1)
I20160129-16:02:06.656(1)?     at meteor://💻app/packages/cfs_collection/packages/cfs_collection.js:249:1
I20160129-16:02:06.656(1)?     at wrappedCallback (meteor://💻app/packages/mongo/collection.js:544:1)
I20160129-16:02:06.656(1)?     at runWithEnvironment (meteor://💻app/packages/meteor/dynamics_nodejs.js:110:1)
I20160129-16:02:06.656(1)?     at meteor://💻app/packages/meteor/dynamics_nodejs.js:123:1
I20160129-16:02:06.656(1)?     at meteor://💻app/packages/mongo/mongo_driver.js:322:1
I20160129-16:02:06.656(1)?     at runWithEnvironment (meteor://💻app/packages/meteor/dynamics_nodejs.js:110:1)
```

**Comment by javascriptlove** [comment]
Ok some more investigation: i think it happens when the file is 0 bytes long (which is ok because the http response code was 200, so it should assume the file is 0 bytes).
