### ISSUE TITLE
gm identify: unable to open file [Migration to S3]

### ISSUE THREAD

**Issue by jasenkoh** [CollectionFS/Meteor-CollectionFS#943]
Hey,

I have added S3 store in my current GridFS store collection and it works fine when I upload new picture, but I have bunch of existing pictures that I want to migrate to S3 but I'm stuck on following error

```
W20160302-20:11:34.758(1)? (STDERR) events.js:72
W20160302-20:11:34.758(1)? (STDERR)         throw er; // Unhandled 'error' event
W20160302-20:11:34.758(1)? (STDERR)               ^
W20160302-20:11:34.759(1)? (STDERR) Error: Command failed: gm identify: Unable to open file (/tmp/gmHEsvPw) [No such file or directory].
W20160302-20:11:34.759(1)? (STDERR) gm identify: Request did not return an image.
W20160302-20:11:34.759(1)? (STDERR)           
W20160302-20:11:34.759(1)? (STDERR)     at ChildProcess._spawn.proc.on.onExit (/home/jasenko/.meteor/packages/cfs_graphicsmagick/.0.0.18.vsfkbq++os+web.browser+web.cordova/npm/node_modules/gm/lib/command.js:279:17)
W20160302-20:11:34.759(1)? (STDERR)     at ChildProcess.emit (events.js:98:17)
W20160302-20:11:34.759(1)? (STDERR)     at maybeClose (child_process.js:766:16)
W20160302-20:11:34.759(1)? (STDERR)     at Socket.<anonymous> (child_process.js:979:11)
W20160302-20:11:34.759(1)? (STDERR)     at Socket.emit (events.js:95:17)
W20160302-20:11:34.759(1)? (STDERR)     at Pipe.close (net.js:466:12)

```

**Comment by AntonAL** [comment]
I had the same problem, when I deployed my app to production.
Something is orphaned in database.
Since my project is under development, I have just dropped production database and restored it from db on development local machine.
