### ISSUE TITLE
Server crashes when downloading files with special characters in filename

### ISSUE THREAD

**Issue by djules75** [CollectionFS/Meteor-CollectionFS#954]
I am using GridFS.
This happened after upgrading to Meteor 1.3. No problem with Meteor 1.2.1.
Not sure if it's a CFS or a Meteor 1.3 issue.

The problem occurs if the filename contains accented characters, for example:
"email d'invitation à contribuer à enrichir un theme.docx"

```
http.js:733
      throw new TypeError('The header content contains invalid characters');
      ^
TypeError: The header content contains invalid characters
  at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
  at /Users/Julien/.meteor/packages/meteor-tool/.1.3.0_3.1ol7cck++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:85:11
  at Array.forEach (native)
  at Array.writeHeaders [as 3] (/Users/Julien/.meteor/packages/meteor-tool/.1.3.0_3.1ol7cck++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:84:35)
  at ClientRequest.<anonymous> (/Users/Julien/.meteor/packages/meteor-tool/.1.3.0_3.1ol7cck++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:149:20)
  at ClientRequest.emit (events.js:95:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1744:21)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
  at Socket.socketOnData [as ondata] (http.js:1639:20)
  at TCP.onread (net.js:528:27)
```

**Comment by mfshiu** [comment]
I have the same issue:

```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at ServerResponse.res.setHeader (C:\Users\mfshi\AppData\Local\.meteor\packages\webapp\1.2.11\npm\node_modules\connect\lib\patch.js:134:22)
    at packages/cfs_http-methods/http.methods.server.api.js:599:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at packages/cfs_http-methods/http.methods.server.api.js:595:1
```

**Comment by djules75** [comment]
I resolved the issue by resorting to monkey patching...

`
  // Fix bug with Collection FS when filenames have accented characters or other special characters
  const originalHandler = FS.HTTP.Handlers.Get;
  FS.HTTP.Handlers.Get = function (ref) {
    ref.filename = ref.filename && removeDiacritics(ref.filename).replace(/[^a-zA-Z0-9.-_ ]+/g, "");
    return originalHandler.call(this, ref);
  };
`

The removeDiacritics fonction is taken from:
http://stackoverflow.com/questions/990904/javascript-remove-accents-diacritics-in-strings
