### ISSUE TITLE
Error: HTTP.methods not implemented on client-side

### ISSUE THREAD

**Issue by mhlavacka** [CollectionFS/Meteor-CollectionFS#957]
Error: HTTP.methods not implemented on client-side
W20160408-03:39:00.782(2)? (STDERR)     
at Object.HTTP.methods (packages/cfs_http-methods/http.methods.client.api.js:5:1)
at Package (packages/cfs_access-point/packages/cfs_access-point.js:840:1)
W20160408-03:39:00.782(2)? (STDERR)     at Package (packages/cfs_access-point/packages/cfs_access-point.js:860:1)

**Comment by nickgermaine** [comment]
I get the same problem on Linux.
